### ISSUE TITLE
Ambiguous content in CHANGELOG.md and GitHub Release v1.7

### ISSUE THREAD

**Issue by patoi** [elastic/ecs#1109] opened 2020-11-11 14:22 UTC
**Description of the issue:**
Ambiguous release v1.7 Is it released or not?

CHANGELOG.md contains information about v1.7, but GitHub Release doesn't contain it, and ECS homepage is refer to v1.6 as "stable" release.

**Any additional context or examples:**

**Comment by webmat** [comment] 2020-11-11 14:28
Dupe of #1108

**Closed by webmat** 2020-11-11 14:28 UTC
Labels: bug
