### ISSUE TITLE
Geoip for both source and destination

### ISSUE THREAD

**Issue by megadevx** [elastic/ecs#29] opened 2018-06-28 14:32 UTC
I do geoip fields for both my source and destination IPs. Would it be useful to include a separation between these two within ECS? I found it hard to differentiate between which geoip is internal and which one is external without it. Or should this just be an specific schema for my particular use case?

Thanks!

**Comment by webmat** [comment] 2018-06-28 14:45
I agree. For security analytics, I've been cramming my source and destination geoip data at `source.geoip` and `destination.geoip` respectively. Because in these kinds of settings, we are observing traffic flows going in both directions. Sometimes our monitored system is the source, and the destination is remote and worth doing geoip on.

I think people have not done it this way in so far, because in operational monitoring cases (e.g. analysing your NGINX web logs), we're only tracking requests going in one direction. Source is always the remote, and destination is always the local address. So in these cases, having `geoip` at the top level was sufficient.

I think we could document both approaches as valid approaches. What do you think, @ruflin ?

**Comment by praseodym** [comment] 2018-06-28 17:30
This is a duplicate of #9.

**Comment by webmat** [comment] 2018-06-28 17:51
True. We can close this one. There's more discussion around that over in #9.

**Closed by webmat** 2018-06-28 17:51 UTC
